services:
  postgres:
    image: postgres:latest
    container_name: novacrust_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_123
      POSTGRES_DB: novacrust_postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
